title: "247Handyman"
description: "Home repairs experts since 2002"
author: "Pedro Duarte"
email: help@247handyman.co.uk
phone1: "07813 246 247"
phone2: "08000 226 247"
baseurl: ""
url: "http://247handyman.co.uk/"

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
